<?xml version="1.0"?>
<robot name="logical_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="logical_camera" params="prefix parent *origin">
    <xacro:property name="length" value="0.2"/>
    <xacro:property name="width" value="0.050"/>
    <xacro:property name="height" value="0.050"/>

    <joint name="${prefix}logical_camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}base_link"/>
    </joint>

    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${height / 2}" />
        <geometry><box size="${width} ${length} ${height}" /></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${height / 2}" />
        <geometry><box size="${width} ${length} ${height}" /></geometry>
      </collision>
      <inertial>
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
        <mass value="1" />
      </inertial>
    </link>
  </xacro:macro>
</robot>
